package mvcc.common;

public enum ErrorCode {
    WRITE_CONFLICT,
    LOCK_CONFLICT,
    LOCK_WAIT_TIMEOUT,
    TRANSACTION_ABORTED,
    TRANSACTION_STATUS_UNKNOWN,
    SNAPSHOT_TOO_OLD,
    STORAGE_UNAVAILABLE,
    ILLEGAL_STATE
}
